name: tasky
description: "A new Flutter project."

publish_to: 'none'  # Keep this for private packages

version: 1.0.0+1

environment:
  sdk: ">=3.5.4 <4.0.0"  # Specify the Dart SDK range to ensure compatibility

dependencies:
  flutter:
    sdk: flutter

  # Core Dependencies
  dio: ^5.7.0                     # For HTTP requests
  bloc: ^9.0.0                    # Business logic component (BLoC)
  flutter_bloc: ^9.0.0            # Flutter BLoC integration
  intl: ^0.20.1                   # For internationalization
  sqflite: ^2.4.1                 # Local SQLite database
  shared_preferences: ^2.3.5      # Local key-value storage
  jwt_decoder: ^2.0.1             # JWT token decoder

  # Utilities
  get_it: ^8.0.3                  # Dependency injection
  path_provider: ^2.1.5           # Access device file paths
  json_annotation: ^4.9.0         # For JSON serialization
  hydrated_bloc: ^10.0.0           # BLoC state persistence with hydration
  flutter_launcher_icons: ^0.14.3 # Launcher icon generation
  flutter_native_splash: ^2.4.4   # Create splash screen
  data_connection_checker_nulls: ^0.0.2  # Network connection checker

  # UI Libraries
  cupertino_icons: ^1.0.8         # iOS-style icons
  iconly: ^1.0.1                  # Icon library
  hexcolor: ^3.0.1                # Color utility for hex values
  chip_list: ^3.1.0               # Chip list widget
  qr_flutter: ^4.1.0              # QR code generator
  mobile_scanner: ^6.0.3  # Check for the latest version on pub.dev
  flutter_svg: ^2.0.17            # SVG support in Flutter
  flutter_svg_icons: ^0.0.1+4     # Predefined SVG icons
  google_fonts: ^6.2.1            # Google Fonts package
  fade_shimmer: ^2.3.0            # Loading shimmer effects
  flutter_staggered_animations: ^1.1.1  # Staggered animations
  image_picker: ^1.1.2  # Image picker for Android and iOS
  file_picker: ^8.1.7 # File picker for Windows

  # Phone utilities
  intl_phone_number_input: ^0.7.4
  libphonenumber_plugin: ^0.3.3

  # Animations
  animations: ^2.0.11             # Flutter animations package
  infinite_scroll_pagination: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0           # Linting rules for best practices
  json_serializable: ^6.9.3       # Auto-generate JSON serialization code
  build_runner: ^2.4.14           # Code generation for json_serializable

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48

flutter_native_splash:
  color: "#5f33e1"
  image: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icon.png